"""initial

Revision ID: 39ff28cbd3b7
Revises: 
Create Date: 2026-05-24 15:29:41.405028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ff28cbd3b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_addr', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('host_name', sa.String(length=120), nullable=False),
    sa.Column('host_email', sa.String(length=200), nullable=False),
    sa.Column('host_pin', sa.String(length=10), nullable=True),
    sa.Column('guest_name', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=True),
    sa.Column('event_title', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.String(length=60), nullable=False),
    sa.Column('event_date_iso', sa.String(length=20), nullable=True),
    sa.Column('event_time', sa.String(length=40), nullable=False),
    sa.Column('rsvp_deadline', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('save_the_date', sa.Boolean(), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=False),
    sa.Column('venue_address', sa.String(length=300), nullable=False),
    sa.Column('venue_lat', sa.Float(), nullable=True),
    sa.Column('venue_lng', sa.Float(), nullable=True),
    sa.Column('dress_code', sa.String(length=120), nullable=True),
    sa.Column('theme', sa.String(length=120), nullable=True),
    sa.Column('colour_palette', sa.String(length=120), nullable=True),
    sa.Column('accent_colour', sa.String(length=20), nullable=True),
    sa.Column('design', sa.String(length=40), nullable=True),
    sa.Column('font', sa.String(length=100), nullable=True),
    sa.Column('pattern', sa.String(length=100), nullable=True),
    sa.Column('decorations', sa.String(length=40), nullable=True),
    sa.Column('extra_notes', sa.Text(), nullable=True),
    sa.Column('music_url', sa.String(length=400), nullable=True),
    sa.Column('music_title', sa.String(length=200), nullable=True),
    sa.Column('music_artist', sa.String(length=200), nullable=True),
    sa.Column('image_1', sa.String(length=300), nullable=True),
    sa.Column('image_2', sa.String(length=300), nullable=True),
    sa.Column('image_3', sa.String(length=300), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('store', sa.String(length=200), nullable=True),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.Column('taken_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('link_token', sa.String(length=16), nullable=False),
    sa.Column('guest_name', sa.String(length=120), nullable=True),
    sa.Column('guest_surname', sa.String(length=120), nullable=True),
    sa.Column('personal_msg', sa.Text(), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_token')
    )
    op.create_table('rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('attending', sa.String(length=10), nullable=False),
    sa.Column('dietary', sa.String(length=300), nullable=True),
    sa.Column('plus_one', sa.String(length=120), nullable=True),
    sa.Column('waitlist', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp')
    op.drop_table('invite_link')
    op.drop_table('gift')
    op.drop_table('announcement')
    op.drop_table('event')
    op.drop_table('audit_log')
    op.drop_table('user')
    # ### end Alembic commands ###
