"""track personalised link rsvps

Revision ID: dada99558376
Revises: 39ff28cbd3b7
Create Date: 2026-05-24 16:14:56.437034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dada99558376'
down_revision = '39ff28cbd3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rsvp_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invite_link_rsvp_id_rsvp', 'rsvp', ['rsvp_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_link', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invite_link_rsvp_id_rsvp', type_='foreignkey')
        batch_op.drop_column('rsvp_id')

    # ### end Alembic commands ###
